# Generated by Django 3.2.5 on 2021-07-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeer',
            table='employee',
        ),
    ]
