# Generated by Django 3.2.5 on 2021-07-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_employeer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeer',
            table='employeer',
        ),
    ]
